"use strict";

const SOURCES = {
  blsIT: "https://www.bls.gov/ooh/computer-and-information-technology/",
  blsSoftware:
    "https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm",
  blsData: "https://www.bls.gov/ooh/math/data-scientists.htm",
  blsCyber:
    "https://www.bls.gov/ooh/computer-and-information-technology/information-security-analysts.htm",
  blsSystems:
    "https://www.bls.gov/ooh/computer-and-information-technology/computer-systems-analysts.htm",
  wef: "https://www.weforum.org/publications/the-future-of-jobs-report-2025/",
  ncs: "https://www.ncs.gov.in/",
  googleSkills: "https://www.skills.google/",
  googleCertificates: "https://grow.google/intl/en_in/certificates/",
  googleDevelopers: "https://www.youtube.com/@GoogleDevelopers",
  microsoftLearn: "https://learn.microsoft.com/en-in/training/",
  microsoftAI: "https://learn.microsoft.com/en-us/ai/",
  awsSkillBuilder: "https://skillbuilder.aws/",
  awsDevelopers: "https://www.youtube.com/@amazonwebservices",
  kaggleLearn: "https://www.kaggle.com/learn",
  kagglePython: "https://www.kaggle.com/learn/python",
  githubSkills: "https://skills.github.com/",
  ciscoNetAcad: "https://www.netacad.com/en",
  freeCodeCamp: "https://www.youtube.com/@freecodecamp",
  unstopInternships: "https://unstop.com/internship-portal",
  unstopHackathons: "https://unstop.com/hackathons",
  hack2skill: "https://hack2skill.com/",
  devpost: "https://devpost.com/hackathons?status=open",
  mlh: "https://mlh.io/",
  mlhEvents: "https://mlh.io/seasons/2026/events",
  mlhGhw: "https://ghw.mlh.io/",
  googleInternships: "https://www.google.com/about/careers/applications/internships",
  googleJobs: "https://www.google.com/about/careers/applications/jobs/results/",
  microsoftStudents: "https://careers.microsoft.com/v2/global/en/students",
  amazonInternships: "https://amazon.jobs/content/en-gb/career-programs/university/internships-for-students",
  ibmInternships: "https://www.ibm.com/in-en/careers/internships",
  nvidiaUniversity: "https://www.nvidia.com/en-eu/about-nvidia/careers/university-recruiting-new/",
  adobeUniversity: "https://www.adobe.com/careers/university.html",
  salesforceInternships: "https://www.salesforce.com/company/careers/university/internships/",
};

const careers = [
  {
    id: "software",
    title: "Software Developer",
    score: 94,
    pay: "$135,980 median",
    growth: 10,
    skills: ["JavaScript", "Python", "Git", "APIs", "SQL"],
    desc: "Design and build software products, services and systems.",
    source: "U.S. BLS OOH",
    url: SOURCES.blsSoftware,
    demands: ["Programming", "APIs", "Version control", "Databases", "Testing"],
    tracks: ["Frontend", "Backend", "Full-stack", "Cloud", "Developer tools"],
  },
  {
    id: "data",
    title: "Data Scientist",
    score: 95,
    pay: "$120,230 median",
    growth: 35,
    skills: ["Python", "Statistics", "SQL", "Machine Learning", "Visualization"],
    desc: "Use analytical tools and statistical methods to extract meaningful insights from data.",
    source: "U.S. BLS OOH",
    url: SOURCES.blsData,
    demands: ["Statistics", "Data cleaning", "Modeling", "Experimentation", "Communication"],
    tracks: ["Analytics", "ML", "Applied AI", "Experimentation", "Business intelligence"],
  },
  {
    id: "cyber",
    title: "Information Security Analyst",
    score: 92,
    pay: "$129,180 median",
    growth: 21,
    skills: ["Networking", "Linux", "Python", "Security", "Risk"],
    desc: "Protect systems and data by evaluating vulnerabilities and improving security controls.",
    source: "U.S. BLS OOH",
    url: SOURCES.blsCyber,
    demands: ["Networking", "Linux", "Threat analysis", "Security controls", "Risk"],
    tracks: ["SOC", "Cloud security", "AppSec", "Threat intelligence", "GRC"],
  },
  {
    id: "systems",
    title: "Computer Systems Analyst",
    score: 88,
    pay: "$105,850 median",
    growth: 8,
    skills: ["Systems Thinking", "SQL", "APIs", "Communication", "Requirements"],
    desc: "Study organizations and technology needs and design systems that improve efficiency.",
    source: "U.S. BLS OOH",
    url: SOURCES.blsSystems,
    demands: ["Requirements", "Process analysis", "SQL", "Systems thinking", "Stakeholder communication"],
    tracks: ["Business systems", "IT consulting", "Product analysis", "Enterprise systems"],
  },
  {
    id: "webdesign",
    title: "Web / Digital Interface Designer",
    score: 80,
    pay: "$104,000 median for digital interface designers",
    growth: 6,
    skills: ["Figma", "UX Research", "Prototyping", "Design Systems", "Communication"],
    desc: "Design digital interfaces and experiences around user needs and interaction.",
    source: "U.S. BLS OOH",
    url: "https://www.bls.gov/ooh/arts-and-design/web-developers.htm",
    demands: ["User research", "Prototyping", "Visual systems", "Interaction design", "Communication"],
    tracks: ["UX", "UI", "Product design", "Design systems", "Research"],
  },
];